import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useEffect } from 'react'

const APP_ID='92c6ad4a'
const APP_KEY='cc57541f5f045e568cc701051f57b2b3'
const URL=`https://api.edamam.com/search?=chicken&app_id=${APP_ID}&app_key=${APP_KEY}`
export async function getStaticProps(context) {
 const response=await axios.get(URL)
 console.log(response.data)
 return{
   props:{
     tosiron:response.data
   }
 }

}

 

export default function Home(tosiron) {
useEffect(() => {
  const fetch=async ()=>{
    const res=await axios.get(URL)
    console.log(res)
  }

   
}, [ ])

  
  return (
    <div className={styles.container}>
      <Head>
        <title>{"Tosiron's recipe | home"}</title>
        <meta name="description" content="Generated by create next app" />
         
      </Head>

       <div className='font-custom '>
         {/* {tosiron.map((item)=>{
           return(
             div
           )
         })} */}
         hello world
       </div>
    </div>
  )
}
